steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - gcr.io/alv-2025/alv-backend:latest
      - .
images:
  - gcr.io/alv-2025/alv-backend:latest
